// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// RgradQ
Eigen::MatrixXd RgradQ(const Rcpp::List& Lt, const Rcpp::List& Lr, const Eigen::MatrixXd& L, const Rcpp::List& B, const Eigen::MatrixXd& U, const Eigen::MatrixXd& V, const Eigen::MatrixXd& W, const double lam, const Eigen::VectorXd& weight);
RcppExport SEXP _mcfda_RgradQ(SEXP LtSEXP, SEXP LrSEXP, SEXP LSEXP, SEXP BSEXP, SEXP USEXP, SEXP VSEXP, SEXP WSEXP, SEXP lamSEXP, SEXP weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Lt(LtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Lr(LrSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type U(USEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type weight(weightSEXP);
    rcpp_result_gen = Rcpp::wrap(RgradQ(Lt, Lr, L, B, U, V, W, lam, weight));
    return rcpp_result_gen;
END_RCPP
}
// RhessianQ
Rcpp::List RhessianQ(const Rcpp::List& Lt, const Rcpp::List& Lr, const Eigen::MatrixXd& S, const Rcpp::List& B, const Eigen::MatrixXd& U, const Eigen::MatrixXd& V, const Eigen::MatrixXd& W, const double lam, const Eigen::VectorXd& weight, const Eigen::MatrixXd& X);
RcppExport SEXP _mcfda_RhessianQ(SEXP LtSEXP, SEXP LrSEXP, SEXP SSEXP, SEXP BSEXP, SEXP USEXP, SEXP VSEXP, SEXP WSEXP, SEXP lamSEXP, SEXP weightSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Lt(LtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Lr(LrSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type U(USEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(RhessianQ(Lt, Lr, S, B, U, V, W, lam, weight, X));
    return rcpp_result_gen;
END_RCPP
}
// crawcov
Rcpp::List crawcov(const Rcpp::List& Lt, const Rcpp::List& Ly, const Eigen::VectorXd weig);
RcppExport SEXP _mcfda_crawcov(SEXP LtSEXP, SEXP LySEXP, SEXP weigSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Lt(LtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Ly(LySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type weig(weigSEXP);
    rcpp_result_gen = Rcpp::wrap(crawcov(Lt, Ly, weig));
    return rcpp_result_gen;
END_RCPP
}
// csmoothcov
Eigen::MatrixXd csmoothcov(const Eigen::Map<Eigen::VectorXd>& bw, const std::string kernel_type, const Eigen::Map<Eigen::MatrixXd>& tPairs, const Eigen::Map<Eigen::MatrixXd>& cxxn, const Eigen::Map<Eigen::VectorXd>& win, const Eigen::Map<Eigen::VectorXd>& xgrid, const Eigen::Map<Eigen::VectorXd>& ygrid, const bool& autoCov, const double delta);
RcppExport SEXP _mcfda_csmoothcov(SEXP bwSEXP, SEXP kernel_typeSEXP, SEXP tPairsSEXP, SEXP cxxnSEXP, SEXP winSEXP, SEXP xgridSEXP, SEXP ygridSEXP, SEXP autoCovSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type bw(bwSEXP);
    Rcpp::traits::input_parameter< const std::string >::type kernel_type(kernel_typeSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type tPairs(tPairsSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type cxxn(cxxnSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type win(winSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type xgrid(xgridSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type ygrid(ygridSEXP);
    Rcpp::traits::input_parameter< const bool& >::type autoCov(autoCovSEXP);
    Rcpp::traits::input_parameter< const double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(csmoothcov(bw, kernel_type, tPairs, cxxn, win, xgrid, ygrid, autoCov, delta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mcfda_RgradQ", (DL_FUNC) &_mcfda_RgradQ, 9},
    {"_mcfda_RhessianQ", (DL_FUNC) &_mcfda_RhessianQ, 10},
    {"_mcfda_crawcov", (DL_FUNC) &_mcfda_crawcov, 3},
    {"_mcfda_csmoothcov", (DL_FUNC) &_mcfda_csmoothcov, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_mcfda(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
