# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RgradQ <- function(Lt, Lr, L, B, U, V, W, lam, weight) {
    .Call('_mcfda_RgradQ', PACKAGE = 'mcfda', Lt, Lr, L, B, U, V, W, lam, weight)
}

RhessianQ <- function(Lt, Lr, S, B, U, V, W, lam, weight, X) {
    .Call('_mcfda_RhessianQ', PACKAGE = 'mcfda', Lt, Lr, S, B, U, V, W, lam, weight, X)
}

crawcov <- function(Lt, Ly, weig) {
    .Call('_mcfda_crawcov', PACKAGE = 'mcfda', Lt, Ly, weig)
}

csmoothcov <- function(bw, kernel_type, tPairs, cxxn, win, xgrid, ygrid, autoCov, delta) {
    .Call('_mcfda_csmoothcov', PACKAGE = 'mcfda', bw, kernel_type, tPairs, cxxn, win, xgrid, ygrid, autoCov, delta)
}

